require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'db/**/*'
    - 'views/**/*'
    - 'config/initializers/devise.rb'
    - 'node_modules/**/**/*'
  TargetRubyVersion: 3.2.2
  SuggestExtensions: false

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'config/routes.rb'
    - 'config/environments/*'

Lint/RedundantSafeNavigation:
  Enabled: false

RSpec/ExampleLength:
  Exclude:
    - 'spec/features/*'
    - 'spec/features/**/*'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/features/*'
    - 'spec/features/**/*'

RSpec/Capybara/FeatureMethods:
  Exclude:
    - 'spec/features/*'
    - 'spec/features/**/*'

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleMemoizedHelpers:
  Max: 10
